name: 'Docker Release'
description: 'Release docker image'
inputs:
  name:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Docker image tags'
    required: true
    default: 'latest'
runs:
  using: 'node16'
  main: 'index.js'